  CREATE TABLE "ADMINS" 
   (	"ADMIN_ID" integer, 
	"ADMIN_NAME" VARCHAR(255) NOT NULL, 
	"ADMIN_PASSWORD" VARCHAR(255) NOT NULL, 
	"ADMIN_EMAIL" VARCHAR(255) NOT NULL, 
	 CONSTRAINT "ADMINS_PK" PRIMARY KEY ("ADMIN_ID")
   ) ;

  CREATE TABLE "CATEGORIES" 
   (	"CATEGORIES_ID" integer, 
	"CATEGORIES_VALUES" VARCHAR(255) NOT NULL, 
	 CONSTRAINT "CATEGORIES_PK" PRIMARY KEY ("CATEGORIES_ID")
   ) ;

  CREATE TABLE "COMPETENCE" 
   (	"COMPETENCE_ID" integer, 
	"COMPETENCE_VALUE" VARCHAR(255), 
	"COMPETENCE_DATE_GIVEN" TIMESTAMP, 
	"COMPETENCE_TASK_ID" integer,
	 CONSTRAINT "COMPETENCE_PK" PRIMARY KEY ("COMPETENCE_ID")
   ) ;

  CREATE TABLE "FEEDBACK" 
   (	"FEEDBACK_ID" integer, 
	"FEEDBACK_VOLUNTEER_ID" integer NOT NULL, 
	"FEEDBACK_TASK_ID" integer NOT NULL, 
	"FEEDBACK_VALUE" VARCHAR(500) NOT NULL, 
	 CONSTRAINT "FEEDBACK_PK" PRIMARY KEY ("FEEDBACK_ID")
   ) ;

  CREATE TABLE "GROUPS" 
   (	"GROUP_ID" integer NOT NULL, 
	"GROUP_NAME" VARCHAR(255) NOT NULL, 
	"GROUP_DESCRIPTION" VARCHAR(500), 
	"GROUP_ADDRESS" VARCHAR(255), 
	 CONSTRAINT "GROUPS_PK" PRIMARY KEY ("GROUP_ID")
   ) ;

  CREATE TABLE "GROUP_VOLUNTEER" 
   (	"GROUP_ID" integer, 
	"VOLUNTEER_ID" integer,
	 CONSTRAINT "GROUP_ID_PK" PRIMARY KEY ("GROUP_ID")
   ) ;

  CREATE TABLE "NON_PROFIT_ORGANIZATION" 
   (	"NPO_ID" integer NOT NULL, 
	"NPO_NAME" VARCHAR(255) NOT NULL, 
	"NPO_EMAIL" VARCHAR(255) NOT NULL, 
	"NPO_PASSWORD" VARCHAR(255), 
	"NPO_PHONENUMBER" integer, 
	"NPO_ADDRESS" VARCHAR(255), 
	"NPO_INFORMATION" VARCHAR(500), 
	"NPO_CATEGORY" VARCHAR(255), 
	 CONSTRAINT "NON_PROFIT_ORGANIZATION_PK" PRIMARY KEY ("NPO_ID")
   ) ;

  CREATE TABLE "PROJECT" 
   (	"PROJECT_ID" integer NOT NULL, 
	"PROJECT_NAME" VARCHAR(255) NOT NULL, 
	"PROJECT_DESCRIPTION" VARCHAR(500), 
	"PROJECT_ADDRESS" VARCHAR(255), 
	"PROJECT_LOCATION" VARCHAR(255), 
	"PROJECT_STATUS" integer, 
	"PROJECT_CREATED_DATE" DATE, 
	"PROJECT_MODIFIED_DATE" DATE, 
	"PROJECT_START_DATE" DATE, 
	"PROJECT_END_DATE" DATE, 
	"PROJECT_REQUIRMENTS" VARCHAR(255), 
	 CONSTRAINT "PROJECT_PK" PRIMARY KEY ("PROJECT_ID")
   ) ;

  CREATE TABLE "PROJECT_NPO" 
   (	"PROJECT_ID" integer, 
	"NPO_ID" integer,
		 CONSTRAINT "PROJECT_ID_PK" PRIMARY KEY ("PROJECT_ID")
   ) ;

  CREATE TABLE "REWARDS" 
   (	"REWARDS_ID" integer, 
	"REWARDS_VALUES" VARCHAR(255),
		 CONSTRAINT "REWARDS_ID_PK" PRIMARY KEY ("REWARDS_ID")
   ) ;

  CREATE TABLE "TASKS" 
   (	"TASK_ID" integer NOT NULL, 
	"TASK_NAME" VARCHAR(255) NOT NULL, 
	"TASK_DESCRPTION" VARCHAR(500) NOT NULL, 
	"TASK_ADRESS" VARCHAR(255), 
	"TASK_LOCATION" VARCHAR(255) NOT NULL, 
	"TASK_STATUS" integer NOT NULL, 
	"TASK_CREATEDDATE" TIMESTAMP, 
	"TASK_MODIFIEDDATE" TIMESTAMP, 
	"TASK_ENDDATE" TIMESTAMP, 
	"TASK_REQUIREMENTS" VARCHAR(255), 
	"TASK_COMPETENCE_FK_ID" integer, 
	"TASK_REWARDS_FK_ID" integer, 
	"TASK_PROJECT_FK_ID" integer, 
	"TASK_CATEGORY_FK_ID" integer, 
	"TASK_USERSTATUS" integer, 
	"TASK_STARTDATE" TIMESTAMP, 
	 CONSTRAINT "TASKS_PK" PRIMARY KEY ("TASK_ID")
   ) ;

  CREATE TABLE "TASKS_NPO" 
   (	"TASK_ID" integer, 
	"NPO_ID" integer,
		 CONSTRAINT "TASKS_PKid" PRIMARY KEY ("TASK_ID")
   ) ;

  CREATE TABLE "TASK_VOLUNTEER" 
   (	"TASK_VOLUNTEER_VOLUNTEER_ID" integer, 
	"TASK_VOLUNTEER_TASK_ID" integer,
		 CONSTRAINT "TASK_VOLUNTEER_TASK_ID" PRIMARY KEY ("TASK_VOLUNTEER_VOLUNTEER_ID")
   ) ;

  CREATE TABLE "VOLUNTEER" 
   (	"VOLUNTEER_ID" integer  NOT NULL, 
	"VOLUNTEER_NAME" VARCHAR(255) NOT NULL, 
	"VOLUNTEER_EMAILADDRESS" VARCHAR(255), 
	"VOLUNTEER_PASSWORD" VARCHAR(255), 
	"VOLUNTEER_PHONENUMBER" integer, 
	"VOLUNTEER_ADDRESS" VARCHAR(255), 
	"VOLUNTEER_CATEGORY" VARCHAR(255), 
	"VOLUNTEER_COMPETENCE_ID" integer, 
	 CONSTRAINT "VOLUNTEER_PK" PRIMARY KEY ("VOLUNTEER_ID")
   ) ;


  CREATE UNIQUE INDEX "ADMINS_PK" ON "ADMINS" ("ADMIN_ID") 
  ;

  CREATE UNIQUE INDEX "CATEGORIES_PK" ON "CATEGORIES" ("CATEGORIES_ID") 
  ;

  CREATE UNIQUE INDEX "COMPETENCE_PK" ON "COMPETENCE" ("COMPETENCE_ID") 
  ;

  CREATE UNIQUE INDEX "FEEDBACK_PK" ON "FEEDBACK" ("FEEDBACK_ID") 
  ;

  CREATE UNIQUE INDEX "GROUPS_PK" ON "GROUPS" ("GROUP_ID") 
  ;

  CREATE UNIQUE INDEX "NON_PROFIT_ORGANIZATION_PK" ON "NON_PROFIT_ORGANIZATION" ("NPO_ID") 
  ;

  CREATE UNIQUE INDEX "PROJECT_PK" ON "PROJECT" ("PROJECT_ID") 
  ;

  CREATE UNIQUE INDEX "TASKS_PK" ON "TASKS" ("TASK_ID") 
  ;

  CREATE UNIQUE INDEX "VOLUNTEER_PK" ON "VOLUNTEER" ("VOLUNTEER_ID") 
  ;

 CREATE VIEW "PROJECTIDNAMEANDNPOID" ("PROJECT_ID", "PROJECT_NAME", "NPO_ID") AS 
SELECT 
    p.project_id,
    p.project_name,
    pn.npo_id
FROM 
    "PROJECT" p
JOIN 
    "PROJECT_NPO" pn ON p.project_id = pn.project_id;